BOARD_TAG    = leonardo
ARDUINO_PORT = /dev/ttyACM*

ARDUINO_LIBS = Analog_Buttons MultiButtons
USER_LIB_PATH = /home/roman/Arduino/libraries

include /usr/share/arduino/Arduino.mk
#LOCAL_INO_SRCS :=
#LOCAL_SRCS      := $(wildcard *.ino)
#
