BOARD_TAG    = uno
ARDUINO_PORT = /dev/cu.usb*

ARDUINO_LIBS = Arduino-Frequency-Counter-Library elapsedMillis Capacitor
USER_LIB_PATH = /home/roman/Arduino/libraries

include /usr/share/arduino/Arduino.mk
