BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0

ARDUINO_LIBS = Arduino-Frequency-Counter-Library elapsedMillis Capacitor MsTimer2
USER_LIB_PATH = /home/roman/Arduino/libraries

include /usr/share/arduino/Arduino.mk
