BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM*

ARDUINO_LIBS = Arduino-Frequency-Counter-Library elapsedMillis Capacitor Nokia_5110_LCD_library
USER_LIB_PATH = /home/roman/Arduino/libraries

include /usr/share/arduino/Arduino.mk
